[versions]
agp = "8.6.1"
compose = "1.8.1"
kotlin = "2.1.20"
ksp = "2.1.20-2.0.0"

kotlinPoet = "2.1.0"


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }


compose = { id = "org.jetbrains.compose", version.ref = "compose" }

kotlinCompose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[libraries]
kotlinPoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlinPoet" }


androidGradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
androidLibraryPlugin = { module = "com.android.library:com.android.library.gradle.plugin", version.ref = "agp" }
androidApplicationPlugin = { module = "com.android.application:com.android.application.gradle.plugin", version.ref = "agp" }
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
composePlugin = { module = "org.jetbrains.compose:org.jetbrains.compose.gradle.plugin", version.ref = "compose" }
kotlinComposePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }



#androidApplicationPlugin = { id = "com.android.application", version.ref = "agp" }
#androidLibraryPlugin = { id = "com.android.library", version.ref = "agp" }
#composePlugin = { id = "org.jetbrains.compose", version.ref = "compose" }
#kotlinComposePlugin = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
#kotlinMultiplatformPlugin = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
#kotlinAndroidPlugin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
#kotlinJvmPlugin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

#ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }