[versions]
androidx-activityCompose = "1.9.3"
androidx-appcompat = "1.7.0"
androidx-constraintlayout = "2.2.0"
androidx-core-ktx = "1.15.0"
androidx-lifecycle = "2.8.3"
androidx-material = "1.12.0"
multiplatform-material = "1.7.3"

kotlin-reflect = "1.9.24"
kotlinx-coroutines = "1.10.1"
kotlinx-datetime = "0.6.1"
kotlinx-io = "0.6.0"

sqlite = "2.5.0-beta01"
androidx-room = "2.7.0-beta01"

koin = "4.0.0"

preference = "1.2.1"

kotlin-serialization-plugin = "1.9.24"
kotlinx-serialization = "1.6.3"

navigation = "2.8.0-alpha10"

decompose = "3.2.2"

moshi = "1.14.0"

quickjs-wrapper = "2.4.0"

quickjs-kt = "1.0.0-alpha13"

zip4j = "2.11.5"

moko-resources = "0.24.5"
jetbrains_kotlin_jvm = "1.9.24"

paging_multiplatform = "3.3.0-alpha02-0.5.1"
coil = "3.1.0"
ktor = "3.1.0"

slf4j = "2.0.16"
log4j-core = "2.20.0"

okio = "3.10.2"

uni_file = "1.0.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-material = { group = "com.google.android.material", name = "material", version.ref = "androidx-material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-io = { group = "org.jetbrains.kotlinx", name = "kotlinx-io-core", version.ref = "kotlinx-io" }



kotlin-reflect = {group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin-reflect"}


koin-core = {group = "io.insert-koin", name = "koin-core", version.ref = "koin"}
koin-android = {group = "io.insert-koin", name = "koin-android", version.ref = "koin"}

sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidx-room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidx-room" }
androidx-room-common = { group = "androidx.room", name = "room-common", version.ref = "androidx-room" }
androidx-room-paging = { group = "androidx.room", name = "room-paging", version.ref = "androidx-room" }

navigation-compose = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "navigation" }

preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference" }

#kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

decompose = { group = "com.arkivanov.decompose", name = "extensions-compose", version.ref = "decompose" }

moshi = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }

quickjs-java = { group = "wang.harlon.quickjs", name = "wrapper-java", version.ref = "quickjs-wrapper" }
quickjs-android = { group = "wang.harlon.quickjs", name = "wrapper-android", version.ref = "quickjs-wrapper" }

quickjs-kt = { module = "io.github.dokar3:quickjs-kt", version.ref = "quickjs-kt" }

zip4j = { module = "net.lingala.zip4j:zip4j", version.ref = "zip4j" }

md3-window-size = { group = "org.jetbrains.compose.material3", name = "material3-window-size-class", version.ref = "multiplatform-material" }

moko-resources = { group = "dev.icerock.moko", name = "resources", version.ref = "moko-resources" }
moko-resources-compose = { group = "dev.icerock.moko", name = "resources-compose", version.ref = "moko-resources" }
moko-resources-generator = { group = "dev.icerock.moko", name = "resources-generator", version.ref = "moko-resources" }

paging-multiplatform-common = { group = "app.cash.paging", name = "paging-common", version.ref = "paging_multiplatform" }
paging-multiplatform-compose = { group = "app.cash.paging", name = "paging-compose-common", version.ref = "paging_multiplatform" }

coil = { group = "io.coil-kt.coil3", name = "coil", version.ref = "coil" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-ktor3 = { group = "io.coil-kt.coil3", name = "coil-network-ktor3", version.ref = "coil" }
coil-gif-android = { group = "io.coil-kt.coil3", name = "coil-gif", version.ref = "coil" }
coil-svg = { group = "io.coil-kt.coil3", name = "coil-svg", version.ref = "coil" }

ktor-client-adroid = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor" }
ktor-client-java = { group = "io.ktor", name = "ktor-client-java", version.ref = "ktor" }

# Logging
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j-core" }
log4j-slf4j-impl = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j-core" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
logback-android = { module = "com.github.tony19:logback-android", version = "3.0.0" }

okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }

uni_file = {module = "com.github.easybangumiorg:UniFile", version.ref = "uni_file"}

[plugins]
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-serialization-plugin" }
mokoResources = { id = "dev.icerock.mobile.multiplatform-resources" }
jetbrainsKotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrains_kotlin_jvm" }