name: release
on:
  push:
    tags:
      - '**'
  workflow_dispatch:
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.5.2
        with:
          submodules: recursive
          token: ${{ secrets.TOKEN }}

      - name: Checkout Private
        uses: actions/checkout@v4
        with:
          repository: 'easybangumiorg/EasyBangumiPrivate'
          token: ${{ secrets.TOKEN }}
          path: 'private'
          ref: main

      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.4
        with:
          java-version: 17

      # Gradle 缓存配置
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
        env:
          RELEASE: true

      - name: Build
        run: |
          ls private
          cp ./private/google-services.json ./android_native/app/google-services.json
          cd android_native
          chmod +x ./gradlew
          ./gradlew :app:assembleRelease
        env:
          APPCENTER_SECRET: ${{ secrets.APPCENTER_SECRET }}
          BUGLY_APPID: ${{ secrets.BUGLY_APPID }}
          RELEASE: true

      - name: Get Version
        id: getVersion
        run: |
          cd android_native
          echo "JSON file content:"
          cat app/build/outputs/apk/release/output-metadata.json
          echo "BANGUMI_VERSION=$(jq -r '.elements[0].versionName' app/build/outputs/apk/release/output-metadata.json)" >> $GITHUB_ENV

      - name: Setup build tool version variable
        shell: bash
        run: |
          echo ${{ env.BANGUMI_VERSION }}
          BUILD_TOOL_VERSION=$(ls /usr/local/lib/android/sdk/build-tools/ | tail -n 1)
          echo "BUILD_TOOL_VERSION=$BUILD_TOOL_VERSION" >> $GITHUB_ENV
          echo Last build tool version is: $BUILD_TOOL_VERSION

      - name: sign-apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: /android_native/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PWD }}
          keyPassword: ${{ secrets.KEY_PWD }}
        env:
          # override default build-tools version (29.0.3) -- optional
          BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}

      - name: rename-apk
        run: |
          mv android_native/app/build/outputs/apk/release/app-release-unsigned-signed.apk easybangumi-${{ env.BANGUMI_VERSION }}.apk

      - name: Archive apk
        uses: actions/upload-artifact@v4
        with:
          name: easybangumi-${{ env.BANGUMI_VERSION }}.apk
          path: easybangumi-${{ env.BANGUMI_VERSION }}.apk
          compression-level: 0

      - name: Release
        run: |
          gh release create -d ${{ env.BANGUMI_VERSION }} easybangumi-${{ env.BANGUMI_VERSION }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: push_mapping
        if: ${{ env.BANGUMI_VERSION }} != "" && ${{ env.BANGUMI_VERSION }} != "."
        run: |
          cd private
          mkdir -p  ./mapping/${{ env.BANGUMI_VERSION }}
          mv -b --suffix=.old ../app/build/outputs/mapping/release/* ./mapping/${{ env.BANGUMI_VERSION }}
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "[auto] mapping"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          force: true
          github_token: ${{ secrets.token }}
          branch: main
          directory: private
          repository: 'easybangumiorg/EasyBangumiPrivate'